/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControleAnimais;
import controller.ControleEspecie;
import controller.ControleRaca;
import exception.DAOException;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Animal;
import model.Especie;
import model.Raca;


public class TelaCadastrarAnimal extends javax.swing.JFrame {

    public int idespecie;
    ControleEspecie controleespecie = new ControleEspecie();
    ControleRaca controleraca = new ControleRaca();
    ControleAnimais controleanimal = new ControleAnimais();
    
    /**
     * Creates new form TelaCadastrarAnimal
     */
    public TelaCadastrarAnimal() throws ParseException, SQLException, DAOException 
    {
        initComponents();
        carregarEspecies();
        idespecie = controleespecie.pesquisar("").get(comboEspecies.getSelectedIndex()).getId();
        carregarRacas();
    }
    
    private void salvarCampos() throws ParseException, SQLException, DAOException
    {
        Animal a = new Animal();
        Raca r = new Raca();
        Especie e = new Especie();
        
        int indexesp = comboEspecies.getSelectedIndex();
        
        e.setId(controleespecie.pesquisar("").get(indexesp).getId());
        e.setNome(controleespecie.pesquisar("").get(indexesp).getNome());
     
        int indexrac = comboRaca.getSelectedIndex();
        
        r.setId(controleraca.listar(e.getId()).get(indexrac).getId());
        r.setEspecie(e);
        r.setNome(controleraca.listar(e.getId()).get(indexrac).getNome());

        a.setNome(cNome.getText());
        a.setProprietario(cProprietario.getText());
        a.setRaca(r);
        controleanimal.setAnimal(a);
    }
    
    private void salvar() throws DAOException, SQLException
    {
        try
        {
            controleanimal.salvar();  
            JOptionPane.showMessageDialog(null, "Pet cadastrado com sucesso.");
            TelaCadastrarAnimal.this.dispose();
        }
        catch(Exception e)
        {

        }
    }
   
    private void carregarEspecies() throws ParseException, SQLException, DAOException
    {
        try
        {
            comboEspecies.removeAllItems();
            for(Especie obj : controleespecie.pesquisar(""))
            {
                comboEspecies.addItem(obj.getNome());
            }
        }
        catch(Exception e)
        {
            
        }        
    }
    
    private void carregarRacas()
    {
        comboRaca.removeAllItems();

        try {
            for(Raca obj: controleraca.listar(idespecie))
            {
                comboRaca.addItem(obj.getNome());
            }   
        } catch (ParseException ex) {
            Logger.getLogger(TelaCadastrarAnimal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastrarAnimal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DAOException ex) {
            Logger.getLogger(TelaCadastrarAnimal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        cNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        comboEspecies = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        comboRaca = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cProprietario = new javax.swing.JTextField();
        bSalvar = new javax.swing.JButton();
        Sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Cadastrar [Animal]");

        jLabel2.setText("Nome do Animal");

        jLabel3.setText("Espécie");

        comboEspecies.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboEspecies.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboEspeciesItemStateChanged(evt);
            }
        });
        comboEspecies.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                comboEspeciesFocusLost(evt);
            }
        });
        comboEspecies.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboEspeciesMouseClicked(evt);
            }
        });

        jLabel4.setText("Raça");

        comboRaca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Proprietário");

        bSalvar.setText("Salvar");
        bSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalvarActionPerformed(evt);
            }
        });

        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4))
                                    .addGap(85, 85, 85))
                                .addComponent(jLabel5))
                            .addComponent(cNome)
                            .addComponent(cProprietario)
                            .addComponent(comboEspecies, 0, 235, Short.MAX_VALUE)
                            .addComponent(comboRaca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 145, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Sair)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cProprietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboEspecies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboRaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSalvar)
                    .addComponent(Sair))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        TelaCadastrarAnimal.this.dispose();
    }//GEN-LAST:event_SairActionPerformed

    private void comboEspeciesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboEspeciesItemStateChanged
        
        try {
            if (comboEspecies.getSelectedIndex() != -1)
            {
                idespecie = controleespecie.pesquisar("").get(comboEspecies.getSelectedIndex()).getId();
            }
            else
            {
                idespecie = 0;
            }
            
            
        } catch (ParseException ex) {
            Logger.getLogger(TelaCadastrarAnimal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastrarAnimal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DAOException ex) {
            Logger.getLogger(TelaCadastrarAnimal.class.getName()).log(Level.SEVERE, null, ex);
        }
      
        carregarRacas();
    }//GEN-LAST:event_comboEspeciesItemStateChanged

    private void bSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalvarActionPerformed
        try {
            salvarCampos();
            salvar();
        } catch (DAOException ex) {
            Logger.getLogger(TelaCadastrarAnimal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastrarAnimal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(TelaCadastrarAnimal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bSalvarActionPerformed

    private void comboEspeciesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboEspeciesMouseClicked
        try {  
            idespecie = controleespecie.pesquisar("").get(comboEspecies.getSelectedIndex()).getId();
        } catch (ParseException ex) {
            Logger.getLogger(TelaCadastrarAnimal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastrarAnimal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DAOException ex) {
            Logger.getLogger(TelaCadastrarAnimal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_comboEspeciesMouseClicked

    private void comboEspeciesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboEspeciesFocusLost

    }//GEN-LAST:event_comboEspeciesFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TelaCadastrarAnimal().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(TelaCadastrarAnimal.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(TelaCadastrarAnimal.class.getName()).log(Level.SEVERE, null, ex);
                } catch (DAOException ex) {
                    Logger.getLogger(TelaCadastrarAnimal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Sair;
    private javax.swing.JButton bSalvar;
    private javax.swing.JTextField cNome;
    private javax.swing.JTextField cProprietario;
    private javax.swing.JComboBox<String> comboEspecies;
    private javax.swing.JComboBox<String> comboRaca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
